project:
  type: website

website:
  title: "Megan Ballard"
  navbar:
    right:
      - href: index.qmd
        text: Home
        image: IMG_0335.jpeg
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



